### ISSUE TITLE
Vl 6180x

### ISSUE THREAD

**Issue by NahuelCarro** [adafruit/Adafruit_VL6180X#11]
Hi, I wanted to see if you could help me with the VL6180x sensor, I tried in many ways but I always get stuck in the 0x18 register, it never gets 0x4. Thank  you 
[y.zip](https://github.com/adafruit/Adafruit_VL6180X/files/3439245/y.zip)

**Comment by ladyada** [comment]
please contact the vendor for tech support - we only accept issues with libraries here. thanks!
