### ISSUE TITLE
How to calculate time with Time of Flight sensor

### ISSUE THREAD

**Issue by Gbouna** [adafruit/Adafruit_VL6180X#12]
Thank you for your tutorial, they were really helpful to get me started.
However i have quite a simple question but i do not know how to get my mind around it.

And according to the datasheet, Effective max convergence time depends on the actual convergence time plus readout averaging sample period setting. Please i want to know how to calculate the convergence time.

This is simply because i want to be able to calculate speed. Since the sensor reads distance, if i know the time, then i can calculate speed.
Thank you

**Comment by ladyada** [comment]
not an issue regarding this code, closing
