### ISSUE TITLE
Wrong values in Initialization sequence

### ISSUE THREAD

**Issue by pramilo** [adafruit/Adafruit_VL6180X#14]
Hi 

Upon reviewing the AN4545 application note from ST and comparing section 9 - the initialization values to load onto the register s- with the library code, the following discrepancies were found:

(code shows is writing the correct values from the most up to date datasheet; your original values are commented)
writeByte(VL6180X_ADDRESS, 0x00e3, 0x01); // was 0x00 in original sample code but 0x1 in applicatio note);
writeByte(VL6180X_ADDRESS, 0x00e4, 0x03); // was 4 in original sample code);

These are listed as "private" registers and recommended to be loaded as per the datasheet.
Any reason for this discrepancy?

Thank you,

**Comment by ladyada** [comment]
unknown, maybe they changed the app note? if you try changing it, see if it works same/better and submit a PR :)

**Comment by sigi77777** [comment]
checked, and the init sequence is repaired now as pramilo suggested. Can close the issue
