### ISSUE TITLE
unable to use 2 VL6180x at the same time like  Vl53L0x

### ISSUE THREAD

**Issue by bidingdream** [adafruit/Adafruit_VL6180X#6]
is there any example like VL53L0x for dual sensor for VL6180?

**Comment by ladyada** [comment]
kinda! :)
wanna try this and report back in the PR if it worked for you?
https://github.com/adafruit/Adafruit_VL6180X/pull/5

**Comment by bidingdream** [comment]
i already try out but there is a error 
C:\Users\job\Documents\Arduino\libraries\Adafruit_VL6180X-master\Adafruit_VL6180X.cpp:49:9: error: prototype for 'boolean Adafruit_VL6180X::begin(TwoWire*)' does not match any in class 'Adafruit_VL6180X'

 boolean Adafruit_VL6180X::begin(TwoWire *theWire) {

         ^

In file included from C:\Users\job\Documents\Arduino\libraries\Adafruit_VL6180X-master\Adafruit_VL6180X.cpp:31:0:

C:\Users\job\Documents\Arduino\libraries\Adafruit_VL6180X-master\Adafruit_VL6180X.h:81:11: error: candidate is: boolean Adafruit_VL6180X::begin(TwoWire*, uint8_t)

   boolean begin(TwoWire *theWire = NULL , uint8_t _i2caddr = VL6180X_DEFAULT_I2C_ADDR);

           ^

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

**Comment by ladyada** [comment]
are you sure you're using the latest files because travis is able to compile for mega just fine
https://travis-ci.org/adafruit/Adafruit_VL6180X

**Comment by bidingdream** [comment]
i tried now it do not have complie problem but its unable to detect the second sensor
can you give me a link to download 
i cannot find the link to download the latest file

**Comment by ladyada** [comment]
https://github.com/kgrech/Adafruit_VL6180X/tree/master/examples

**Comment by ajlapp** [comment]
I'm not able to replicate this function on a Teensy 3.6...I can see one sensor but multiple sensors cannot be found.

The address change example seems to work, but I can't find the sensor after changing the address when more than one is on the bus.

I also don't seem to be able to get the "shutdown" function working.
